scheduler_project/schedule/urls.py
import django.contrib.auth.views
from django.contrib import admin
from django.urls import path
from . import views
from django.views.static import serve

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('events_list/', views.events_list, name='events_list'),
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('create_event/', views.create_event, name='create_event'),
    path('suggest_event/', views.suggest_event, name='suggest_event'),
    path('about/', views.about, name='about'),
    # AJAX
    path('ajax_like/', views.ajax_like, name='ajax_like'),
    path('ajax_lead/', views.ajax_lead, name='ajax_lead'),
    # PASSWORD RESET
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name=
        'schedule/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name=
        'schedule/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name=
        'schedule/password_reset_complete.html'), name='password_reset_complete'),

    path('subjects_list/', views.subjects_list, name='subjects_list'),
    path('users_list/', views.users_list, name='users_list'),
    path('user_details/<int:index>', views.user_details, name='user_details'),
    path('user_edit/<int:index>', views.user_edit, name='user_edit'),
    path('delete_user/<int:index>', views.delete_user, name='delete_user'),
    path('subject_edit/<int:index>', views.subject_edit, name='subject_edit'),
    path('delete_subject/<int:index>', views.delete_subject, name='delete_subject'),
    path('email_client', views.email_client, name='email_client'),
    path('email_notification', views.email_notification, name='email_notification'),
    path('event_edit/<int:index>', views.event_edit, name='event_edit'),
    path('delete_event/<int:index>', views.delete_event, name='delete_event'),
    path('my_profile/', views.my_profile, name='my_profile'),
    # path('change_password/', views.change_password, name='change_password'),
    path('event_details/<int:index>', views.event_details, name='event_details'),
    path('polls_list', views.polls_list, name='polls_list'),
    path('poll_details/<int:index>', views.poll_details, name='poll_details'),
    path('draft_edit/<int:index>', views.draft_edit, name='draft_edit'),
    path('403/', views.handler_403, name='403'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})
]

scheduler_project/scheduler_project/urls.py
from django.contrib import admin
from django.urls import path, include

handler403 = 'schedule.views.handler_403'
handler404 = 'schedule.views.handler_404'
handler400 = 'schedule.views.handler_400'
handler500 = 'schedule.views.handler_500'

urlpatterns = [

     path('', include('schedule.urls')),

 ]

scheduler_project/schedule/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.dispatch import receiver
from django.db.models.signals import post_migrate
from django.contrib.auth import get_user_model


class Event(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Szkic'),
        ('publish', 'Opublikowano')
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250,
                            unique_for_date='planning_date', default=None)
    description = models.TextField(verbose_name='opis wydarzenia', blank=True, max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    planning_date = models.DateTimeField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    organizer = models.ForeignKey(User, on_delete=models.CASCADE)
    want_to_listen = models.ManyToManyField(User, related_name='want_to_listen', default=None, blank=True, null=True)
    status = models.CharField(max_length=15,
                              choices=STATUS_CHOICES,
                              default='publish')
    duration = models.IntegerField(blank=True, null=True)
    icon = models.FileField(upload_to='icons/', default='icons/default.png', null=True)
    attachment = models.FileField(upload_to='attachments/', blank=True, null=True)
    link = models.CharField(max_length=1000, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Event, self).save(*args, **kwargs)

    # topics

    class Meta:
        ordering = ('planning_date',)

    def __str__ (self):
        return self.title


class Polls(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None, blank=True)
    if_active = models.BooleanField(default=False, blank=True)
    since_active = models.DateField(blank=True, null=True, default=None)
    till_active = models.DateField(blank=True, null=True, default=None)
    if_sent_notification = models.BooleanField(blank=True, null=True, default=False)


class Dates(models.Model):
    poll = models.ForeignKey(Polls, on_delete=models.CASCADE)
    date = models.DateTimeField(blank=True, null=True)
    count = models.IntegerField(null=True, blank=True, default=0)
    users = models.ManyToManyField(User, related_name='users', default=None, blank=True)


class Subject(models.Model):
    proposer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date='created', default=None)
    description = models.TextField(verbose_name='opis tematu', max_length=400)
    created = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='like', default=None, blank=True)
    like_count = models.IntegerField(default='0')
    want_to_lead = models.ManyToManyField(User, related_name='want_to_lead', default=None, blank=True)
    lead_count = models.IntegerField(default='0')

    def save (self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Subject, self).save(*args, **kwargs)

    def __str__ (self):
        return self.title

    class Meta:
        ordering = ('-created',)


class EmailSet(models.Model):
    delay_leader = models.IntegerField(default=3)
    delay_all = models.IntegerField(default=2)
    # USTAWIENIA SERWERA POCZTY
    EMAIL_BACKEND = models.CharField(max_length=50, default="django.core.mail.backends.smtp.EmailBackend")
    EMAIL_HOST = models.CharField(max_length=30)
    EMAIL_PORT = models.IntegerField(default=587)
    EMAIL_HOST_USER = models.CharField(max_length=50)
    EMAIL_HOST_PASSWORD = models.BinaryField(max_length=100)
    EMAIL_USE_TLS = models.BooleanField(default=True)
    DEFAULT_FROM_EMAIL = models.CharField(max_length=50)
    EMAIL_HEADER = models.CharField(max_length=50)
    NONCE = models.BinaryField(max_length=100, blank=True)


class EventNotification(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    leader = models.ForeignKey(User, on_delete=models.CASCADE)
    if_sent_leader = models.BooleanField(default=False)
    if_sent_all = models.BooleanField(default=False)
    settings = models.ForeignKey(EmailSet, on_delete=models.CASCADE, default=1)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=1000)
    if_edited = models.BooleanField(default=False)
    if_deleted = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

scheduler_project/schedule/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.db import models
from .models import Event, Subject, Comment
import datetime
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from .decorators import unauthenticated_user, allowed_users


class UserFullnameChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        fullname = obj.get_full_name()
        return fullname


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class CreateEvent(ModelForm):
    organizer = UserFullnameChoiceField(queryset=User.objects.all())
    planning_date = forms.DateTimeField(initial=datetime.date.today)
    icon = forms.FileField(required=False)
    attachment = forms.FileField(required=False)
    link = forms.CharField(required=False)

    class Meta:
        model = Event
        fields = ('title', 'description', 'organizer', 'planning_date', 'duration', 'icon', 'attachment', 'link')


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = ('title', 'description')


class ChangePassword(PasswordChangeForm):
    error_messages = dict(PasswordChangeForm.error_messages, **{
        'passwords_match': ("Nowe hasło nie może być takie samo jak poprzednie"),
    })


    def clean_new_password1(self):
        old_pass = self.cleaned_data.get('old_password')
        new_pass = self.cleaned_data.get('new_password1')
        if old_pass and new_pass:
            if old_pass == new_pass:
                raise forms.ValidationError(
                    self.error_messages['passwords_match'], code='passwords_match'
                )
        return new_pass

#@allowed_users(allowed_roles=['admin', 'employee'])
class AddComment(ModelForm):
    class Meta:
        model = Comment
        fields = ('author','event','content','if_edited','if_deleted')

scheduler_project/schedule/templates/schedule/about.html
{% extends 'schedule/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<br>
<h2 style="text-align:center;">O aplikacji</h2>


<div class="container" style="max-width:1200px;">
    <hr>
    <br>
    <br>
<h1 class="text-center"> Aplikacja do organizowania szkoleń dla pracowników </h1>
    <br>
<h2 class="text-center"> Projekt zespołowy na zlecenie Comarch</h2>
    <br><br><hr><br>
<h4> Autorzy: </h4>
    <br>
    <ul>
    <li> <a href="https://github.com/nadrowskyy"> Tomek N. [lider]</li>
    <li> <a href="https://github.com/rabarbartek">Bartek K. </a></li>
    <li> <a href="https://github.com/mrudawski"> Michał R. </a></li>
    <li> <a href="https://github.com/hurin0"> Bartek Ż. </li>
    </ul>
    <br>
    <hr>
    <br>
    <a href="https://github.com/nadrowskyy/organize-application"><h4>Oficjalne repozytorium projektu</a></h4>
<br><hr><br>
    <p style="text-align: center">
        Całość prezentowanej strony internetowej stanowi własność ww. autorów i jest utworem w rozumieniu ustawy
        z dnia 4 lutego 1994 r. o prawie autorskim i prawach pokrewnych (Dz. U. Nr 90, poz. 631). Żadna jej część nie
        może być rozpowszechniana lub kopiowana w jakikolwiek sposób bez zgody autorów.
    </p>

    <p style="text-align: center">
        W naszym serwisie umieszczone są łącza (linki) do innych serwisów internetowych. Informujemy, że nie ponosimy
        żadnej odpowiedzialności za treści zawarte w innych serwisach.
    </p>
<br><hr>
    <p style="text-align: center">
        The entire website is the property of the above-mentioned authors and it is regulated by Polish law -
        [ Ustawa z dnia 4 lutego 1994 r. o prawie autorskim i prawach pokrewnych (Dz. U. Nr 90, poz. 631) ].
        Replicating and sharing the source code is strictly prohibited without the consent of the authors.
    </p>

    <p style="text-align: center">
        We are not responsible for the content of links to external sources posted on the website.
    </p>
    <hr>
    <p style="text-align: center">
        © 2021
    </p>

</div>
</body>
</html>
{% endblock %}

scheduler_project/schedule/templates/schedule/create_event.html
{% extends 'schedule/base.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Utwórz szkolenie</title>


</head>

<body>

<br><br>
<h2 style="text-align:center;">UTWÓRZ SZKOLENIE</h2>
<br>

<div class="container" style="max-width:800px;">

<form action="" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div class="row pub-padd">
    <div class="col-md-12 col-lg-6 pub-text">
        <div class="pub-border">
        <input type="radio" onchange="hideB(this)" name="publish" id="radio_publish" checked value="True">
        <label data-toggle="tooltip" data-placement="right" title="Szkolenie zostanie odrazu opublikowane
i będzie widoczne na liście szkoleń." for="radio_publish">Publikuj</label>
        </div>
        </div>
    <div class="col-md-12 col-lg-6 pub-text">
        <div class="pub-border">
            <input type="radio" onchange="hideA(this)" name="publish" id="radio_draft" value="False">
        <label data-toggle="tooltip" data-placement="right" title="Szkolenie będzie widoczne tylko dla administratora
oraz organizatora szkolenia jako szkic w zakładce szkolenia." for="radio_draft">Szkic</label>
        </div>
        </div>
  </div>
    <br><br>
    <div class="row">
            {% for message in messages %}
                <errormsg>{{ message }}</errormsg>
            <br><br>
            {% endfor %}
        </div>
    <div class="form-group">
        <label for="title">Temat szkolenia<sup>* **</sup></label>
        <input class="form-control" id="title" name="title" placeholder="Wpisz temat szkolenia" required type="text" maxlength="200">
    </div>

    <div class="form-group">
        <label>Opis szkolenia<sup>*</sup></label>
        <textarea class="form-control" name="description" id="description2" placeholder="Opisz szkolenie" required rows="4" maxlength="1000"></textarea>
    </div>

    <div class="form-group">
        <label for="link">Lokalizacja szkolenia (miejsce lub link)</label>
        <input class="form-control" id="link" name="link" placeholder="Podaj lokalizację szkolenia" type="text">
    </div>

    <div class="form-group">

        <label for="organizer">Organizator<sup>* **</sup></label><br>
            <select class="selectOrganizer" id="organizer" name="organizer" style="width: 100%;">
                {% for i in fullnames %}
                <option value="{{i.id}}">{{i.first_name}} {{i.last_name}} ({{i.email}})</option>
                {% endfor %}
md
            </select>
    </div>

    <div class="row">
    <div class="col-md-12 col-lg-6">
      <label for="planning_date">Data i godzina rozpoczęcia<sup>*</sup></label>
        <input class="form-control" id="planning_date" min="{% now 'Y-m-d\TH:i' %}" name="planning_date" type="datetime-local"
               value="{% now 'Y-m-d\TH:i' %}" required>
    </div>
    <div class="col-md-12 col-lg-6">
     <label for="duration">Czas trwania (min.)<sup>*</sup></label>
        <input class="form-control" id="duration" min="1" name="duration" placeholder="1" type="number" required>
    </div>
  </div>
<br>

    <div id="poll" style="display:none;">
        <div class="card h-200">
	<div class="card-body">
    <div class="row">
            <div class="col-md-12 col-lg-6">
                <label>Czy ankieta ma być aktywna?</label><br>
                    <input  id="active_true" onchange="pollReqB(this)" name="if_active" type="radio" value="True">
                    <label data-toggle="tooltip" data-placement="right" title="Ankieta będzie widoczna w zakładce 'Głosowanie'.
Należy podać minimum dwa unikalne terminy głosowania oraz
daty dostępności ankiety." for="active_true">Tak</label>
                    <input  id="active_false" onchange="pollReqA(this)" name="if_active" type="radio" value="False" checked>
                    <label data-toggle="tooltip" data-placement="right" title="Ankieta nie będzie wiczona w zakładce 'Głosowanie'.
Nie jest wymagane podawanie czasu dostępności ankiety oraz proponowanych terminów spotkań
ale jeśli chcemy dodać terminy dostępności to muszą to być minimum dwa terminy." for="active_false">Nie</label>
                <br><br>
            </div>

        </div>
        <div class="row">
        <div class="col-md-12 col-lg-6">
            <label for="poll_avaible_since">Od kiedy ankieta ma być dostępna<sup>***</sup></label>
                <input class="form-control" id="poll_avaible_since" min="{% now 'Y-m-d\TH:i' %}" name="poll_avaible_since" type="date">
        </div>
        <div class="col-md-12 col-lg-6">
        <label for="poll_avaible">Do kiedy ankieta ma być dostępna<sup>***</sup></label>
            <input class="form-control" id="poll_avaible" name="poll_avaible" type="date">
            <br>
        </div>

        </div>
        <div class="row">
            <div class="col-md-12 col-lg-6">
               <br>
                <span data-toggle="tooltip" data-placement="down" title="Należy podać minimum dwa terminy spotkań
dla utworzenia aktywnej ankiety. Jeśli ankieta będzie nieaktywna
podawanie terminów nie jest konieczne ale
jeśli będziemy chcieli dodać terminy do nieaktywnej ankiety
to również muszą to być minimum dwa terminy.">TERMINY</span>: &nbsp; &nbsp;
                <button id="add_date" class="btn btn-secondary" style="font-family: 'Oswald', sans-serif;" type="button">Dodaj termin</button>
            </div>
        </div>
        <br>

        <div class="card h-200">

	    <div class="card-body">

        <div id="plan_container" class="row">

        </div>

        </div>

        </div>
        <sup>***</sup> Pola wymagane do utworzenia aktywnej ankiety
    </div>
    </div>


        </div>
    <br>
    <div class="row">
    <div class="col-md-12 col-lg-6">
    <div class="form-group">
        <div class="form-group files">
            <label>Prześlij ikonę</label>
            <input accept="image/*" id="id_icon" name="icon" type="file">
        </div>
    </div>
    </div>

    <div class="col-md-12 col-lg-6">
    <div class="form-group">
              <div class="form-group files">
                <label>Prześlij załącznik</label>
                <input accept="application/pdf" id="id_attachment" name="attachment" type="file">
              </div>
    </div>
    </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12 col-lg-6">
            <sup>*</sup> Pola wymagane do opublikowania szkolenia<br>
            <sup>**</sup> Pola wymagane do utworzenia szkicu szkolenia
        </div>
    </div>
    <br>
    <center><button class="btn btn-secondary" style="width:20%;font-family: 'Oswald', sans-serif;" type="submit">Utwórz</button></center>
    <br>
</form>
</div>




    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>

<script>

    $(document).ready(function() {
    $('.selectOrganizer').select2();
    $('#add_date').click(function () {
       $('#plan_container').append('<div class="col-md-12 col-lg-6"> <input class="form-control" name="planning_date_draft" type="datetime-local" required><button class="remove_date btn btn-secondary" style="font-family: \'Oswald\', sans-serif;" type="button">Usuń termin</button><br><br></div>')
    });
    });

</script>
<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
</script>
<script>
    function hideA(x) {
   if (x.checked) {
     document.getElementById("poll").style.display = "block";
     //document.getElementById("planning_date_div").style.display = "none";
   }
        $('#radio_publish').prop('checked',false);
     $('#radio_draft').prop('checked',true);
   $('#description2').prop('required',false);
   $('#duration').prop('required',false);
   $('#planning_date').prop('required',false);
 }

 function hideB(x) {
   if (x.checked) {
     document.getElementById("poll").style.display = "none";
     //document.getElementById("planning_date_div").style.display = "inline-block";

   }
   $('#description2').prop('required',true);
   $('#duration').prop('required',true);
   $('#planning_date').prop('required',true);
 }

     function pollReqA(x) {
   $('#poll_avaible_since').prop('required',false);
   $('#poll_avaible').prop('required',false);
   $('#planning_date_draft_1').prop('required',false);
   $('#planning_date_draft_2').prop('required',false);
 }

 function pollReqB(x) {
   $('#poll_avaible').prop('required',true);
   $('#poll_avaible_since').prop('required',true);
   $('#planning_date_draft_1').prop('required',true);
   $('#planning_date_draft_2').prop('required',true);

 }

 $(document).on('click', '.remove_date', function () {
     $(this).closest('div').remove();
 });
</script>


</body>
</html>

{% endblock %}

scheduler_project/schedule/templates/schedule/drafts_list.html
{% extends 'schedule/base.html' %}
{% load static %}
{% load auth_extras %}
{% block content %}


{% if not list %}
    <br>
    <errormsg>Nie znaleziono szkiców</errormsg>

{% endif %}

<div class="container">

    <br>
    <center><h2>LISTA SZKICÓW</h2></center>
    <hr>

<div class="row">
    {% for i in list %}


            <div class="col-lg-3 col-md-4 col-sm-5">
                    <p style="text-align:center;"><img class="rounded-circle" src="{{MEDIA_URL}}{{i.icon}}" alt="" width="140" height="140"></p>
                <center>
                    <h3>{{i.title}}</h3>
                    <h7>{{i.planning_date|date:"d.m.Y H:i"}} ({{i.planning_date|date:"l"}})</h7>
                    <br>
                    <h6>Prowadzi: {{i.organizer.first_name}} {{i.organizer.last_name}}</h6>
                     <p style="text-align:center;"><a class="btn btn-secondary" href="{% url 'event_details' i.id %}" role="button">Szczegóły »</a>
                         {% if not request.user|has_group:"admin" %}
                            {% if request.user == i.organizer %}
                                <a href="{% url 'draft_edit' i.id %}"><img src="{% static 'images/icons/edit.png' %}" style="text-align:right; width:25px; height:25px;"></a>
                            {% endif %}
                         {% else %}
                            <a href="{% url 'draft_edit' i.id %}"><img src="{% static 'images/icons/edit.png' %}" style="text-align:right; width:25px; height:25px;"></a>

                            <a href="{% url 'delete_event' i.id %}" onclick="return confirm('Czy na pewno chcesz usunąć spotkanie {{i.title}}? \n\nOperacji nie będzie można cofnąć!');"><img src="{% static 'images/icons/delete.png' %}" style="text-align:right; width:25px; height:25px;"></a>
                         {% endif %}
                    <br>
                </center>
            </div>
    {% endfor %}
    </div>
</div>


{% endblock %}

scheduler_project/schedule/templates/schedule/email_client.html
{% extends 'schedule/base.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Ustawienia klienta poczty</title>


</head>

<body >

<br>
<h2 style="text-align:center;">USTAWIENIA SERWERA EMAIL</h2>
<br>
<div class="spinner-border text-primary"
        id="loader" role="status">
        <span class="sr-only">Loading...</span>
</div>
<div id="data" class="container col-5" style="max-width:400px;">

<form action="" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div class="form-group">
		<label for="email_host">Nazwa serwera:</label>
		<input class="form-control" id="email_host" name="email_host" placeholder="Nazwa serwera" required type="text" value="{{ settings.EMAIL_HOST }}">
    </div>

	<div class="form-group">
		<label for="from_email">Wyświetlany nadawca wiadomości:</label>
		<input class="form-control" id="from_email" name="from_email" placeholder="&quot;Nazwa&quot; <adres@domena.xyz>" required type="text" value="{{ settings.EMAIL_HEADER }}">
    </div>

    <div class="form-group">
		<label for="username">Użytkownik:</label>
		<input class="form-control" id="username" name="username" placeholder="Użytkownik" required type="text" value="{{ settings.EMAIL_HOST_USER }}">
	</div>

    <div class="form-group">
		<label for="password">Hasło:</label>
		<input class="form-control" id="password" name="password" placeholder="Hasło" required type="password" value="{{ password }}">
    </div>

	<div class="form-group">
      	<label for="port">Port:</label>
		<input class="form-control" id="port" name="port" placeholder="Numer portu" required type="number" value="{{ settings.EMAIL_PORT }}">
	</div>
	<div class="form-group">
     	<label>Używaj TLS</label><br>
		<input  id="tls_true" name="if_tls" type="radio" {% if settings.EMAIL_USE_TLS == 1 %} checked {% endif %} value="True">
		<label  for="tls_true">Tak</label>
		<input  id="tls_false" name="if_tls" type="radio" {% if settings.EMAIL_USE_TLS == 0 %} checked {% endif %} value="False">
		<label  for="tls_false">Nie</label>
	</div>
	<div class="form-group">
		<label for="delay_leader">Wyprzedzenie powiadomień dla organizatora (dni):</label>
		<input class="form-control" id="delay_leader" name="delay_leader" required type="number" value="{{ settings.delay_leader }}">
	</div>
	<div class="form-group">
		<label for="delay_all">Wyprzedzenie powiadomień dla wszystkich użytkowników (dni):</label>
		<input class="form-control" id="delay_all" name="delay_all" required type="number" value="{{ settings.delay_all }}">
	</div>


<br>

    <center><button id="buttonA" class="btn btn-secondary" style="width:20%;font-family: 'Oswald', sans-serif;" type="submit">Aktualizuj</button></center>

</form>
</div>



{% if error %}

<script>
$(document).ready(function() {
  alert("{{error}}");
});
</script>

{% endif %}


<script type='text/javascript'>

$(document).ready(function(){
  // Show image container
  $("#loader").hide();
  $("#buttonA").click(function(){
  	$("#loader").show();
  })

});

</script>
</body>
</html>

{% endblock %}

scheduler_project/schedule/templates/schedule/email_template.html
{% load static %}
{% if user %}
Cześć! {{ user.first_name }}
W najbliższym czasie masz szkolenia do zorganizowania, oto ich lista:
{% for event in events %}
{{event.title}}
{{event.planning_date}}
{{event.description}}
{% endfor %}
{% else %}
Hej! Może zainteresuą Cie nasze nadchodzące szkolenia:
{% for event in events %}
{{event.title}}
{{event.planning_date}}
{{event.description}}
{% endfor %}
{% endif %}

Twój Zespół FFT.

        

scheduler_project/schedule/templates/schedule/password_reset_complete.html
{% extends "schedule/base.html" %}

{% block title %}Password reset{% endblock %}

{% block content %}
    <br>
    <h2 style="text-align:center;">Resetowanie hasła</h2>
    <br>
    <div class="container col-5" style="max-width:400px;">
    <p>Hasło zostało zmienione. Możesz się już <a href="{% url "login" %}">zalogować</a>.</p>
    </div>
{% endblock %}